### ISSUE TITLE
Terraform starts Skytap VMs before entire environment is built.

### ISSUE THREAD

**Issue by thewellington** [skytap/terraform-provider-skytap#33]
### Terraform Version

```
[thewellington:~/Development … ops_stacks/demo_workspace] dev(+41/-14) 1 ± terraform -v
2019/04/19 12:31:10 [INFO] Terraform version: 0.11.13
2019/04/19 12:31:10 [INFO] Go runtime version: go1.12
2019/04/19 12:31:10 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.13/bin/terraform", "-v"}
2019/04/19 12:31:10 [DEBUG] Attempting to open CLI config file: /Users/thewellington/.terraformrc
2019/04/19 12:31:10 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/04/19 12:31:10 [INFO] CLI command args: []string{"version", "-v"}
Terraform v0.11.13
2019/04/19 12:31:10 [DEBUG] checking for provider in "."
2019/04/19 12:31:10 [DEBUG] checking for provider in "/usr/local/Cellar/terraform/0.11.13/bin"
2019/04/19 12:31:10 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2019/04/19 12:31:10 [DEBUG] found provider "terraform-provider-skytap_v0.9.0_x4"
2019/04/19 12:31:10 [DEBUG] found valid plugin: "skytap", "0.9.0", "/Users/thewellington/Development/2019_CAB_devops_stacks/demo_workspace/.terraform/plugins/darwin_amd64/terraform-provider-skytap_v0.9.0_x4"
+ provider.skytap v0.9.0

2019/04/19 12:31:11 [DEBUG] plugin: waiting for all plugin processes to complete...
[thewellington:~/Development … ops_stacks/demo_workspace] dev(+41/-14) ±
```

### Affected Resource(s)
- skytap_vm

### Terraform Configuration Files
```hcl
# 2019-05 Skytap Customer Advisory Board (CAB) Demo
# DevOps Stacks
# Bill Wellington (bill@skytap.com)


# It's a good idea to name the deployment - let's get this from user input
variable "deployment_name" {}

# We can grab our skytap creds from environment variables
variable "skytap_username" {}
variable "skytap_api_token" {}

provider "skytap" {
  username = "${var.skytap_username}"
  api_token = "${var.skytap_api_token}"
}

# Create a new environment
resource "skytap_environment" "environment" {
  template_id = "1597515"                # this is an empty environment that I prepred for this demo
  name = "${var.deployment_name}"
  description = "${var.deployment_name} Environment created by Terraform"
}

# Create a new network in the environment
resource "skytap_network" "network" {
  environment_id = "${skytap_environment.environment.id}"
  name = "Network"
  domain = "skytap.services"
  subnet = "192.168.1.0/24"
  gateway = "192.168.1.254"
  tunnelable = true
}

# we are going to need to distribute IP addresses to these machines
variable "ip_addreses" {
  default = {
    "0" = "192.168.1.1"
    "1" = "192.168.1.2"
    "2" = "192.168.1.3"
    "3" = "192.168.1.4"
    "4" = "192.168.1.5"
    "5" = "192.168.1.6"
    "6" = "192.168.1.7"
    "7" = "192.168.1.8"
    "8" = "192.168.1.9"
    "9" = "192.168.1.10"
  }
}

# Add some VMs to the environment
resource "skytap_vm" "webservers" {
  count = 10
  template_id = "1599587"
  vm_id = "45214703"
  environment_id = "${skytap_environment.environment.id}"
  name = "web-${count.index}"
  network_interface = {
    interface_type = "vmxnet3"
    network_id = "${skytap_network.network.id}"
    ip = "${lookup(var.ip_addreses, count.index)}"
    hostname = "web-${count.index}"
  }
}



```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://gist.github.com/thewellington/5e6e56621cec1190d6a0a7fa77cf85dc

### Expected Behavior
I should have ten VMs named `web-0` through `web-9`, each connected to the defined network, each with an assigned ip address, and each with an assigned hostname (also `web-0` through `web-9`)

### Actual Behavior
Some number less that ten VMs are spun up correctly.  Additionally typically two more VMs are created, but not configured completely and not started.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Troubleshooting Steps

- If I set the `count` of the `skytap_vm.webservers` resource to 1, and run `terraform apply` I will get a properly configured VM.  If I then increment the count and re-run `terraform apply` I will get two properly configured VMs.  I can increment this all the way to 10 and ge the environment that I need, but I will have had to run `terraform apply` ten times.

- If I set the count to 1 and replace the `count.index` on line 61 with an intiger 0-9 I can create any single VM instance with the correct name and IP address

These two items tell me that all my inputs are correct and clean.

I believe that I get the following 422 errors from Skytap because the provider has started some of the VMs before finishing the configuration of all the VMs in the environment.  This puts the environment into a busy state and generating the 422 status code.

```
* skytap_vm.webservers.0: error updating interface: PUT https://cloud.skytap.com/v2/configurations/50987338/vms/45261189/interfaces/nic-25567309-46275305-0: 422 (request "f12ca889-2d76-4cbd-9569-a2a357298aac")
2019-04-19T12:17:09.863-0700 [DEBUG] plugin.terraform-provider-skytap_v0.9.0_x4: 2019/04/19 12:17:09 [ERR] plugin: plugin server: accept unix /var/folders/q2/553k9lms2nbd9n_0ssm59c9r0000gn/T/plugin388855419: use of closed network connection
* skytap_vm.webservers[1]: 1 error(s) occurred:

* skytap_vm.webservers.1: error updating interface: PUT https://cloud.skytap.com/v2/configurations/50987338/vms/45261193/interfaces/nic-25567309-46275309-0: 422 (request "58a0f100-06b2-493f-9481-0be9c96a1042")
* skytap_vm.webservers[3]: 1 error(s) occurred:

* skytap_vm.webservers.3: error updating interface: PUT https://cloud.skytap.com/v2/configurations/50987338/vms/45261191/interfaces/nic-25567309-46275307-0: 422 (request "9d6f2f82-bc07-4dfc-bc00-3581e2a2a0c4")
* skytap_vm.webservers[2]: 1 error(s) occurred:
2019-04-19T12:17:09.866-0700 [DEBUG] plugin: plugin process exited: path=/Users/thewellington/Development/2019_CAB_devops_stacks/demo_workspace/.terraform/plugins/darwin_amd64/terraform-provider-skytap_v0.9.0_x4

* skytap_vm.webservers.2: error creating VM: PUT https://cloud.skytap.com/configurations/50987338: 422 (request "3df6be94-2232-4ee9-be29-baea6c197b2a")  with options: "(skytap.CreateVMRequest) {\n TemplateID: (string) (len=7) \"1599587\",\n VMID: (string) (len=8) \"45214703\"\n}\n"
* skytap_vm.webservers[4]: 1 error(s) occurred:

* skytap_vm.webservers.4: error updating interface: PUT https://cloud.skytap.com/v2/configurations/50987338/vms/45261187/interfaces/nic-25567309-46275303-0: 422 (request "c779b8d7-7756-492b-a32e-24dd4eb1642a")
```

**Comment by ja6a** [comment]
I think the solution to this problem is to implement in code the guidelines stated on the Skytap API documentation. The docs say that any API script must pay careful attention to the state of the skytap resources when making requests. The relevant page is available here: https://help.skytap.com/api-busy-bp.html

**Comment by ja6a** [comment]
1. We have identified the cause of the issue. The problems is that we are assigning IP addresses in the terraform - but we are getting conflicts since we have an automatic network. This is caused because a number of network interfaces receive IP addresses prior to an additional network request which then assigns the specified address. The workaround is to assign the IP addresses to a range unlikely to be used by Skytap, e.g. starting 192.168.1.100. Of course this isn't a permanent fix. A better solution would be reconsider how the networks are configured in the terraform provider.

2. This error was possible to uncover due to the improvements made in the reliability and logging in the underlying SDK.
2.1 with the help of the document (https://help.skytap.com/api-busy-bp.html) mentioned above - every post or put or delete request is both pre-checked and post-checked. Pre-checking involves confirming the system is in the expected state. Post-checking involves confirming the change has been made successfully. This is achieved by using a mixture of polling and retrying the request. 
2.2 the pre-checking is done by checking either the environment or vm state. Each request knows prior to its call what the state should be. A retry will be done 60 times with a 10 second wait.
2.3 once the state is OK: the request is issued. The response code is checked as per the document. If the status is 200 the client polls the relevant object and inspects it. If there is a discrepancy the client waits for 10 seconds and then polls again. 
2.4 if the response code is 409, 422, 423, 429 the error is read and the request is made again.
2.5 steps 2.2-2.4 will be done up to 60 times.

**Comment by ja6a** [comment]
Other fixes:
1. don't attempt to start an environment if it is empty.
2. don't expect the 'routable' argument to be always false. It can be null if there is no network in an environment.

**Comment by thewellington** [comment]
This issue is resolved in v.0.11.1
